# This is simply for testing the API endpoints without having to implement code elsewhere

# To use this, install the "REST Client" extension in VS Code and click "Send Request"

GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/?email=nicholasbailey@csus.edu

###

GET http://localhost:3000/api/users/652cd8dc7ea563b05aafd984

###

POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "Document",
    "email": "test-22@csus.edu",
    "password": "aaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "roleId": 1,
    "statusId": 1,
    "firstQuestion": "First",
    "secondQuestion": "Second",
    "firstAnswer": "test1",
    "secondAnswer": "test2"
}

###

DELETE http://localhost:3000/api/users/652cd8dc7ea563b05aafd984


###

PATCH http://localhost:3000/api/users/652b3f604faa28af881c609a
Content-Type: application/json

{
    "firstName": "New"
}

###

GET http://localhost:3000/api/login?email=testbobby%2540csus.edu&password=Bobburger1!

###

GET http://localhost:3000/api/meetings/

###

GET http://localhost:3000/api/meetings/?instructorId=652cd8dc7ea563b05aafd984

###

GET http://localhost:3000/api/meetings/?userId=654580101c7d3ca3348babc6

###

DELETE http://localhost:3000/api/meetings/654a3fcd19d04ce274c067a0

###

POST http://localhost:3000/api/meetings/
Content-Type: application/json

{
    "instructor_id": "652cd8dc7ea563b05aafd984",
    "attendees": [
        "650b7ba7c0d2c23aed28e286",
        "651387e6eb42079f16a273b9",
        "652d6e2245a69c7758ad15b0"
    ]
}

###

PATCH http://localhost:3000/api/meetings/652927f92d44d19f60f65c8c
Content-Type: application/json

{
    "newAttendee": "652927f92d44d19f60f65c8c"
}