# This is simply for testing the API endpoints without having to implement code elsewhere

# To use this, install the "REST Client" extension in VS Code and click "Send Request"

GET http://localhost:3001/users

###

GET http://localhost:3001/users/652b3f604faa28af881c609a

###

POST http://localhost:3001/users/
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "Te",
    "email": "aaa@test.com",
    "password": "Boburger1!",
    "roleId": 1,
    "statusId": 1
}

###

DELETE http://localhost:3001/users/6521ddfc920d19c62b60b3c1


###

PATCH http://localhost:3001/users/652b3f604faa28af881c609a
Content-Type: application/json

{
    "firstName": "New"
}

###

GET http://localhost:3001/login?email=testbobby%2540csus.edu&password=Bobburger1!